// Code generated by protoc-gen-go. DO NOT EDIT.
// source: extractor.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_UNKNOWN StatusCode = 0
	StatusCode_OK      StatusCode = 1
	StatusCode_FAILED  StatusCode = 2
)

var StatusCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "FAILED",
}

var StatusCode_value = map[string]int32{
	"UNKNOWN": 0,
	"OK":      1,
	"FAILED":  2,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_39fd19a8b349f81d, []int{0}
}

type BlockInfo struct {
	ParentHash           []byte   `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	UncleHash            []byte   `protobuf:"bytes,2,opt,name=uncle_hash,json=uncleHash,proto3" json:"uncle_hash,omitempty"`
	Coinbase             []byte   `protobuf:"bytes,3,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	Root                 []byte   `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	TxHash               []byte   `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ReceiptHash          []byte   `protobuf:"bytes,6,opt,name=receipt_hash,json=receiptHash,proto3" json:"receipt_hash,omitempty"`
	Bloom                []byte   `protobuf:"bytes,7,opt,name=bloom,proto3" json:"bloom,omitempty"`
	Difficulty           uint64   `protobuf:"varint,8,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Number               uint64   `protobuf:"varint,9,opt,name=number,proto3" json:"number,omitempty"`
	GasLimit             uint64   `protobuf:"varint,10,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed              uint64   `protobuf:"varint,11,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Time                 uint64   `protobuf:"varint,12,opt,name=time,proto3" json:"time,omitempty"`
	Extra                []byte   `protobuf:"bytes,13,opt,name=extra,proto3" json:"extra,omitempty"`
	MixDigest            []byte   `protobuf:"bytes,14,opt,name=mix_digest,json=mixDigest,proto3" json:"mix_digest,omitempty"`
	Nonce                uint64   `protobuf:"varint,15,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Size                 uint64   `protobuf:"varint,16,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockInfo) Reset()         { *m = BlockInfo{} }
func (m *BlockInfo) String() string { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()    {}
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_39fd19a8b349f81d, []int{0}
}

func (m *BlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInfo.Unmarshal(m, b)
}
func (m *BlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInfo.Marshal(b, m, deterministic)
}
func (m *BlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInfo.Merge(m, src)
}
func (m *BlockInfo) XXX_Size() int {
	return xxx_messageInfo_BlockInfo.Size(m)
}
func (m *BlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInfo proto.InternalMessageInfo

func (m *BlockInfo) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockInfo) GetUncleHash() []byte {
	if m != nil {
		return m.UncleHash
	}
	return nil
}

func (m *BlockInfo) GetCoinbase() []byte {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

func (m *BlockInfo) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *BlockInfo) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *BlockInfo) GetReceiptHash() []byte {
	if m != nil {
		return m.ReceiptHash
	}
	return nil
}

func (m *BlockInfo) GetBloom() []byte {
	if m != nil {
		return m.Bloom
	}
	return nil
}

func (m *BlockInfo) GetDifficulty() uint64 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *BlockInfo) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockInfo) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *BlockInfo) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *BlockInfo) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *BlockInfo) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *BlockInfo) GetMixDigest() []byte {
	if m != nil {
		return m.MixDigest
	}
	return nil
}

func (m *BlockInfo) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockInfo) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Status struct {
	Code                 StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=extractor.StatusCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_39fd19a8b349f81d, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_UNKNOWN
}

func init() {
	proto.RegisterEnum("extractor.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*BlockInfo)(nil), "extractor.BlockInfo")
	proto.RegisterType((*Status)(nil), "extractor.Status")
}

func init() { proto.RegisterFile("extractor.proto", fileDescriptor_39fd19a8b349f81d) }

var fileDescriptor_39fd19a8b349f81d = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0xdd, 0x6e, 0xd3, 0x40,
	0x10, 0x85, 0x49, 0x9a, 0x3a, 0xf1, 0x24, 0xb4, 0xd1, 0x8a, 0x9f, 0x05, 0x04, 0x94, 0x5e, 0x15,
	0xa4, 0x24, 0x82, 0x3c, 0x01, 0xa5, 0x20, 0xaa, 0x56, 0xa9, 0x14, 0x54, 0x21, 0x71, 0x63, 0xad,
	0xd7, 0x13, 0x7b, 0x85, 0xed, 0x8d, 0xf6, 0x47, 0x32, 0x3c, 0x15, 0x8f, 0x88, 0x76, 0x36, 0x4a,
	0x7a, 0xe5, 0x39, 0xdf, 0x19, 0x1f, 0x8f, 0x67, 0x17, 0x4e, 0xb1, 0x73, 0x46, 0x48, 0xa7, 0xcd,
	0x7c, 0x6b, 0xb4, 0xd3, 0x2c, 0xdd, 0x83, 0xf3, 0x7f, 0x47, 0x90, 0x5e, 0xd6, 0x5a, 0xfe, 0xbe,
	0x6e, 0x37, 0x9a, 0xbd, 0x85, 0xf1, 0x56, 0x18, 0x6c, 0x5d, 0x56, 0x09, 0x5b, 0xf1, 0xde, 0x59,
	0xef, 0x62, 0xb2, 0x86, 0x88, 0xbe, 0x0b, 0x5b, 0xb1, 0xd7, 0x00, 0xbe, 0x95, 0x35, 0x46, 0xbf,
	0x4f, 0x7e, 0x4a, 0x84, 0xec, 0x97, 0x30, 0x92, 0x5a, 0xb5, 0xb9, 0xb0, 0xc8, 0x8f, 0xc8, 0xdc,
	0x6b, 0xc6, 0x60, 0x60, 0xb4, 0x76, 0x7c, 0x40, 0x9c, 0x6a, 0xf6, 0x1c, 0x86, 0xae, 0x8b, 0x59,
	0xc7, 0x84, 0x13, 0xd7, 0x51, 0xd0, 0x3b, 0x98, 0x18, 0x94, 0xa8, 0xb6, 0xbb, 0x49, 0x12, 0x72,
	0xc7, 0x3b, 0x46, 0x2d, 0x4f, 0xe0, 0x38, 0xaf, 0xb5, 0x6e, 0xf8, 0x90, 0xbc, 0x28, 0xd8, 0x1b,
	0x80, 0x42, 0x6d, 0x36, 0x4a, 0xfa, 0xda, 0xfd, 0xe1, 0xa3, 0xb3, 0xde, 0xc5, 0x60, 0xfd, 0x80,
	0xb0, 0x67, 0x90, 0xb4, 0xbe, 0xc9, 0xd1, 0xf0, 0x94, 0xbc, 0x9d, 0x62, 0xaf, 0x20, 0x2d, 0x85,
	0xcd, 0x6a, 0xd5, 0x28, 0xc7, 0x81, 0xac, 0x51, 0x29, 0xec, 0x6d, 0xd0, 0xec, 0x05, 0x84, 0x3a,
	0xf3, 0x16, 0x0b, 0x3e, 0x26, 0x6f, 0x58, 0x0a, 0x7b, 0x6f, 0xb1, 0x08, 0x7f, 0xe5, 0x54, 0x83,
	0x7c, 0x42, 0x98, 0xea, 0x30, 0x19, 0x2d, 0x98, 0x3f, 0x8e, 0x93, 0x91, 0x08, 0xab, 0x6b, 0x54,
	0x97, 0x15, 0xaa, 0x44, 0xeb, 0xf8, 0x49, 0x5c, 0x5d, 0xa3, 0xba, 0x2b, 0x02, 0xe1, 0xa5, 0x56,
	0xb7, 0x12, 0xf9, 0x29, 0x25, 0x45, 0x11, 0xe2, 0xad, 0xfa, 0x8b, 0x7c, 0x1a, 0xe3, 0x43, 0x7d,
	0xbe, 0x84, 0xe4, 0x87, 0x13, 0xce, 0x5b, 0xf6, 0x1e, 0x06, 0x52, 0x17, 0x48, 0xe7, 0x74, 0xf2,
	0xe9, 0xe9, 0xfc, 0x70, 0xce, 0xb1, 0xe1, 0x8b, 0x2e, 0x70, 0x4d, 0x2d, 0x1f, 0x66, 0x00, 0x07,
	0xc6, 0xc6, 0x30, 0xbc, 0x5f, 0xdd, 0xac, 0xee, 0x7e, 0xae, 0xa6, 0x8f, 0x58, 0x02, 0xfd, 0xbb,
	0x9b, 0x69, 0x8f, 0x01, 0x24, 0xdf, 0x3e, 0x5f, 0xdf, 0x7e, 0xbd, 0x9a, 0xf6, 0x2f, 0x97, 0xbf,
	0x3e, 0x96, 0xca, 0x55, 0x3e, 0x9f, 0x4b, 0xdd, 0x2c, 0x0a, 0x2d, 0x73, 0x5f, 0xd7, 0x0b, 0x74,
	0x15, 0x1a, 0xf4, 0xcd, 0x2c, 0x0f, 0x37, 0x66, 0xb6, 0xff, 0xdc, 0x82, 0xae, 0x55, 0x9e, 0xd0,
	0x63, 0xf9, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x34, 0xe4, 0x84, 0xc6, 0x70, 0x02, 0x00, 0x00,
}
